### ISSUE TITLE
PostgreSQL Provider acting weird

### ISSUE THREAD

**Issue by freetnt5852** [dirigeants/klasa-pieces#96]
I tried switching from mongodb to postgresql, guild configs and stuff worked fine but with points monitor which uses klasa-member-gateway plugin, it keeps spamming `error: value too long for type character varying(18)` and all I'm doing is incrementing points, then also w my afk command it errors about `error: integer out of range` I'm not even using integers here, just updating a boolean and a string.

**Comment by kyranet** [comment]
I have added a getter in Gateway to tell providers the length of the id, should be fixed in https://github.com/dirigeants/klasa-pieces/commit/28c6de00dbdff677a36bf57763a45f1f91b569bd.

Make sure to update `klasa-member-gateway` to https://github.com/dirigeants/klasa-member-gateway/commit/d7999ddc547f006e0d04bb987f664dbf3bd3abde
